### ISSUE TITLE
Description flushes when cloning experiment

### ISSUE THREAD

**Issue by iakremnev** [allegroai/clearml-server#44]
Bug: when I try to type a description in a cloned experiment, it constantly disappears after about 5 seconds of typing -- no matter the length of the string typed.

Here's a recording of this issue at 18 fps: [video.zip](https://github.com/allegroai/trains-server/files/4732231/video.zip)

**Comment by iakremnev** [comment]
I also can't see where's the experiment description when I manage to type it and enqueue the experiment with trains-agent.

**Comment by bmartinn** [comment]
Thanks @iakremnev for the video!
The bug is verified on the demo-server  :(

The description / comment should be shown under the "Info" tab , in the "Description"  section.
You can also always edit it there (so after you clone, you can edit the comment, also after running the experiment). That said, there is also an issue with new-line in the comment/description section, that will be fixed in the next patch version.

**Comment by iakremnev** [comment]
Found it, thanks!

**Comment by jkhenning** [comment]
Closing this as this is already fixed in the latest ClearML Server versions.
